### ISSUE TITLE
Output inferred SV type in shorthand notation (i.e., manta-like VCF format)

### ISSUE THREAD

**Issue by weizhu365** [EUCANCan/variant-extractor#4]
Dear Rodrigo;

I like the idea to homogenization SVs and those rules.  Your example script vcf_to_csv.py has also demonstrated that the infer and return was implemented successfully.  However, in your example script normalize_vcf.py, the inferred SV type is not returned as described.  

For example, little is changed after running normalize_vcf.py on one DEL prediction from Svaba:

```bash
### DEL from original svaba output
1       811313  402487592:1     T       ]1:811714]T     22      PASS    DISC_MAPQ=30;EVDNC=DSCRD;IMPRECISE;MAPQ=30;MATEID=402487592:2;MATENM=-1;NM=-1;NUMPARTS=0;SCTG=1:811313(-)-1:811714(+)__1_808501_833501D;SPAN=401;SVTYPE=BND     GT:AD:DP:GQ:PL:SR:DR:LR:LO      0/1:9:27:22.1:22.1,0,45.2:0:9:-22.12:22.58

### from the output of normalize_vcf.py
1       811313  402487592:1     T       ]1:811714]T     22.00   PASS    DISC_MAPQ=30;EVDNC=DSCRD;IMPRECISE;MAPQ=30;MATEID=402487592:2;MATENM=-1;NM=-1;NUMPARTS=0;SCTG=1:811313(-)-1:811714(+)__1_808501_833501D;SPAN=401;SVTYPE=BND     GT:AD:DP:GQ:PL:SR:DR:LR:LO      0/1:9:27:22.1:22.1,0,45.2:0:9:-22.12:22.58
```

It will be very helpful to have inferred SV output into the consistent format (for example, manta-like short-hand notation VCF format), so as to be processed by the other tools like SURVIVOR.  I think that the essential functions have already been developed in VariantExtractor APIs.  It might not be hard for you to make the change I am looking for. 

Thanks and kind regards,

Wei 

Wei Zhu

**Comment by Rapsssito** [comment]
Hi @weizhu365, thanks for the feedback! However, the example script is just an example (as general as possible). Feel free to download it and make your own modifications. For this use case, you could change the last lines to something like this (untested code):

```python
def change_to_shorthand(variant_record):
  # Change the ALT field
  variant_record.alt = f'<{variant_record.variant_type.name}>'
  # You will probably need to add some values to the INFO field such as "END=" (except for insertions)
  if variant_record.variant_type != VariantType.INS:
     variant_record.info['END'] = variant_record.end

# Previous main code (...)
for variant_record in records:
   if variant_record.variant_type == VariantType.DUP or variant_record.variant_type == VariantType.INV:
      change_to_shorthand(variant_record)
   # You must decide an indel threshold for deletions and insertions
   elif (variant_record.variant_type == VariantType.DEL or variant_record.variant_type == VariantType.INS) and variant_record.length > indel_threshold:
      change_to_shorthand(variant_record)
   output_vcf.write(str(variant_record)+'\n')
```

Check the [available documentation](https://eucancan.github.io/variant-extractor/variant_extractor.html) for more information about the API.
